#!/bin/bash

PROGRAM_NAME=$0
cd `dirname $PROGRAM_NAME`
source machinefunc.sh

function usage()
{
    cat << EOF

Usage: $PROGRAM_NAME [arguments]

Arguments:
    -h, --help          Print Help and exit
    -i, --install       Perform installation
        --reinstall     Remove installed parts and perform installation
    -c, --clean         Remove installed parts 
    -p, --part=PART     Specify a part to install or clean
    -l, --list-part     List all installable parts
        --prefix        Set the install path

EOF
}

if [[ "$(whoami)" != "root" ]];then
    error "You need to be root to run installation"
    exit 1
fi

if [[ $# == 0 ]];then
    usage
    exit 0
fi

short_opts="hicp:l"
long_opts="help,install,clean,part:,list-part,reinstall,prefix:"
TEMP=$(getopt -n $PROGRAM_NAME -o "$short_opts" -l "$long_opts" -- "$@") || \
{ error "Error parsing arguments. Try $PROGRAM_NAME --help"; exit 1; }

PART="all"
EXE=""
PREFIX=$install_path

eval set -- "$TEMP"
while true; do
    case $1 in
        -h|--help)
            usage
            exit 0
        ;;
        -i|--install)
            if [[ "$EXE" == "" ]];then
                EXE="install"
            fi
            shift; continue
        ;;
        --reinstall)
            if [[ "$EXE" == "" ]];then
                EXE="reinstall"
            fi
            shift; continue
        ;;
        -c|--clean)
            if [[ "$EXE" == "" ]];then
                EXE="clean"
            fi
            shift; continue
        ;;
        -p|--part)
            PART="$2"; shift 2; continue
        ;;
        -l|--list-part)
            if [[ "$EXE" == "" ]];then
                EXE="listparts"
            fi
            shift; continue
        ;;
        --prefix)
            PREFIX=$(realpath "$2"); shift 2; continue
        ;;
        --)
            # no more arguments to parse
            break
        ;;
        *)
            error "Unknow option " $1
            exit 1
        ;;
    esac
done

export MACHINE_INIT_PREFIX=$PREFIX
export MACHINE_INIT_WORK_DIR=`pwd`

case $EXE in
    install)
        installParts $PART
    ;;
    reinstall)
        cleanParts $PART
        installParts $PART
    ;;
    clean)
        cleanParts $PART
    ;;
    listparts)
        listAllParts
    ;;
    *)
        normalp "Nothing has been done"
    ;;
esac

unset MACHINE_INIT_PREFIX
unset MACHINE_INIT_WORK_DIR
