version: "3.0"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:2.345
    ports:
      - "50000:50000"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /work/app/jenkins/jenkins_home:/var/jenkins_home
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      TZ: "Asia/Shanghai"
