version: "3.0"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.29
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /work/app/mysql/mysql:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: password
