version: "3.0"
services:
  nginx:
    container_name: nginx
    image: nginx:1.21.6
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - "php"
    volumes:
      - /work/app/nginx/conf.d:/etc/nginx/conf.d
      - /work/app/www:/usr/share/nginx/html
      - /work/app/nginx/log:/var/log/nginx
      - /work/app/nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      LANGUAGE: "C.UTF-8"
    networks:
      - nginx-net
  php:
    container_name: phpfpm
    image: php:7.2-fpm
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - /work/app/www:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      LANGUAGE: "C.UTF-8"
    networks:
      - nginx-net
networks:
  nginx-net:
    driver: bridge
