version: "3.0"
services:
  registry:
    container_name: registrysvr
    image: "registry:2.8.1"
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - /work/app/registry/registry:/var/lib/registry
      - /work/app/registry/registry-svr.yml:/etc/docker/registry/config.yml
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - registry-net
  web:
    container_name: registryweb
    image: "hyper/docker-registry-web:v0.1.2"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - registry
    volumes:
      - /work/app/registry/registry:/var/lib/registry
      - /work/app/registry/registry-web.yml:/conf/config.yml
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - registry-net
networks:
  registry-net:
    driver: bridge